CREATE TABLE IF NOT EXISTS lavori (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lavoro TEXT NOT NULL,
  fatto INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lista_spesa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  articolo TEXT NOT NULL,
  ordine INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS storico_spesa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  articolo TEXT NOT NULL UNIQUE,
  conteggio INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS categorie (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL UNIQUE,
  colore TEXT NOT NULL DEFAULT '#000000'
);

CREATE TABLE IF NOT EXISTS spese (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  categoria TEXT NOT NULL,
  importo INTEGER NOT NULL,
  note TEXT NOT NULL,
  id_vacanza INTEGER NOT NULL DEFAULT 0,
  extra INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vacanze (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  attiva INTEGER NOT NULL DEFAULT 1,
  data_inizio TEXT NOT NULL,
  data_fine TEXT
);

CREATE TABLE IF NOT EXISTS spese_sandro (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  descrizione TEXT NOT NULL,
  importo REAL NOT NULL,
  pagato INTEGER NOT NULL DEFAULT 0,
  data_pagamento TEXT
);

CREATE TABLE IF NOT EXISTS impostazioni (
  chiave TEXT PRIMARY KEY,
  valore TEXT
);
